### ISSUE TITLE
Can't create more than one vm 

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-templates#114]
## Steps 
- Create VM1 
- Try to create another vm 
## Issue 
- it result the following error inside the server and can't create vm again : 
```
[Wed16 14:48] - base.py           :201 :service-64f4bd4f-e5dd-46fe-8776-4aa1ebd05d27 - ERROR    - error executing action _monitor:
Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-robot/zerorobot/template/state.py", line 78, in check
    state = self.get(category, tag)
  File "/opt/code/github/zero-os/0-robot/zerorobot/template/state.py", line 57, in get
    raise StateCategoryNotExistsError("category %s does not exist" % category)
zerorobot.template.state.StateCategoryNotExistsError: category actions does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-robot/zerorobot/task/task.py", line 79, in execute
    self._result = self._func()
  File "/opt/code/github/zero-os/0-templates/templates/vm/vm.py", line 37, in _monitor
    self.state.check('actions', 'install', 'ok')
  File "/opt/code/github/zero-os/0-robot/zerorobot/template/state.py", line 85, in check
    raise StateCheckError(err_msg)
zerorobot.template.state.StateCheckError: check for state actions:install:ok failed

```
## vm1
```
services:

  - github.com/zero-os/0-templates/vm/0.0.1__vm1:
      flist: https://hub.gig.tech/gig-bootable/ubuntu:16.04.flist
      nics:
        - type: default
        - name: "vm1"
actions:
  - service: vm1
    actions: ['install']
```
## vm2
```
services:

  - github.com/zero-os/0-templates/vm/0.0.1__vm2:
      flist: https://hub.gig.tech/gig-bootable/ubuntu:16.04.flist
      nics:
        - type: default
        - name: "vm2"
actions:
  - service: vm2
    actions: ['install']

```

**Comment by zaibon** [comment]
The error you show is actually normal. This is triggered by the _monitor action that can only start running once the VM is installed. So when you first create the service, before the install action is done, you get this. This is not an error and that doesn't mean that you VM is not created.

**Comment by Dinaamagdy** [comment]
but what happen that  vm didn't created

**Comment by Dinaamagdy** [comment]
it was my bad , I used same port for both vm, when I change it, it  works
