### ISSUE TITLE
Can't create namespace using action install in namespace template

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-templates#122]
### steps:
- create zdb server using zdb template
- try to create namspace using the namespace template

#### zdb blueprint
```yaml
services:
    - github.com/zero-os/0-templates/zerodb/0.0.1__myzdb:
          sync: True
          mode: 'user'
          path: '/mnt/data'
                   
actions:
    - template: 'github.com/zero-os/0-templates/zerodb/0.0.1'
      service: 'myzdb'
      actions: ['install']
```

#### namespace blueprint 
```yaml
services:
    - github.com/zero-os/0-templates/namespace/0.0.1__myns:
          zerodb: 'myzdb'
          size: 2
          password: 'password'
          
actions:
    - template: 'github.com/zero-os/0-templates/namespace/0.0.1'
      service: 'myns'
      actions: ['install']
```

### stacktrace
```
[Tue22 11:46] - base.py           :201 :service-c4fce725-565d-4525-809d-02fe6205e975 - ERROR    - error executing action install:
Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-robot/zerorobot/task/task.py", line 79, in execute
    self._result = self._func()
  File "/opt/code/github/zero-os/0-templates/templates/zerodb/zerodb.py", line 91, in info
    return self._zerodb_sal.info
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/sal/zerodb/zerodb.py", line 85, in info
    info = self.node.client.btrfs.info(self.path)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/BtrfsManager.py", line 48, in info
    return self._client.json('btrfs.info', {'mountpoint': mountpoint})
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/ContainerManager.py", line 126, in json
    result = self.sync(command, arguments, tags=tags, id=id)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/ContainerManager.py", line 116, in sync
    raise ResultError(msg='%s' % result.data, code=result.code)
JumpScale9Lib.clients.zero_os.Response.ResultError: "(ERROR): [ ERROR: not a valid btrfs filesystem: /mnt/data\n]"

```

> I can create a namspace for the same zdb using ```namespace_create``` action in zdb template.
```python
In [3]: zdb = robot.services.get(name='myzdb')

In [4]: zdb.schedule_action('namespace_create', args={'name':'test_zdb_tempalte'})
Out[4]: namespace_create

In [5]: zdb.schedule_action('namespace_list').result
Out[5]: [{'name': 'test_zdb_tempalte', 'password': None, 'public': True, 'size': None}]
```

**Comment by grimpy** [comment]
Currently zdb can only be installed on btrfs or a subpath of btrfs
