### ISSUE TITLE
ErrorConditionObject: 'cloudinit' when using 0-template for GW

### ISSUE THREAD

**Issue by yveskerwyn** [zero-os/0-templates#125]
Using `development` branch of Zero-OS:

```python
zt_config_instance_name = 'my_zt_account'
zt_client = j.clients.zerotier.get(instance=zt_config_instance_name)
zt_app_network_name = 'app_network'
auto_assign_range2 = '10.147.20.0/24'
zt_app_network = zt_client.network_create(public=False, name=zt_app_network_name , auto_assign=True, subnet=auto_assign_range2)
zt_app_network_id = zt_app_network.id

zrobot_instance_name = 'my_robot'
zrobot = j.clients.zrobot.robots[zrobot_instance_name]

gw_data = {
    'hostname': 'mygw',
    'domain': 'lan',
    'networks': [
        {
        'name': 'public',
        'type': 'default',
        }, 
        {
        'name': 'private',
        'type': 'zerotier',
        'id': zt_app_network_id,
        'ztClient' : zt_client
         }]
    }

gw_service = zrobot.services.find_or_create(GW_UID, service_name='mygw', data=gw_data)
gw_service.schedule_action('install').wait(die=True)
```

traceback:
```python
 Traceback (most recent call last):                                                                                                                      │6-2c1d0ac4dc33 - INFO     - Monitoring node local
  File "/opt/code/github/zero-os/0-robot/zerorobot/task/task.py", line 79, in execute                                                                   │2018-05-23T16:17:31.139Z: logger I > [1]zrobot 2|[Wed23 16:17] - node.py           :78  :service-459a6e1f-8b1c-466f-9356-2c1d0ac4dc33 - INFO     - s
    self._result = self._func()                                                                                                                         │torage pool 0cc47ae545dc_fscache doesn't exist on node 0cc47ae545dc
  File "/opt/code/github/zero-os/0-templates/templates/gateway/gateway.py", line 28, in install                                                         │2018-05-23T16:17:31.139Z: logger I > [1]4e766110-91f4-4d4f-8de2-08aef236d7d0 2|[Wed23 16:17] - node.py           :78  :service-459a6e1f-8b1c-466f-93
    gateway_sal = self._gateway_sal                                                                                                                     │56-2c1d0ac4dc33 - INFO     - storage pool 0cc47ae545dc_fscache doesn't exist on node 0cc47ae545dc
  File "/opt/code/github/zero-os/0-templates/templates/gateway/gateway.py", line 24, in _gateway_sal                                                    │
    return self._node_sal.primitives.from_dict('gateway', self.data)                                                                                    ├────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/sal/primitives.py", line 144, in from_dict                                        │-41ea-b6e3-d6b0a3255fe2/task_list/947b8fb6-5f99-48d0-a18f-db2480f5397a HTTP/1.1" 200 1870 0.008001
    gw.from_dict(data)                                                                                                                                  │[Wed23 16:16] - node.py           :32  :service-401db68f-189f-44a2-aabc-e16c97c4038a - INFO     - Monitoring node my_packet_node_service
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zero_os/sal/gateway/gateway.py", line 226, in from_dict                                   │[Wed23 16:16] - node.py           :78  :service-401db68f-189f-44a2-aabc-e16c97c4038a - INFO     - storage pool 0cc47ae545dc_fscache doesn't exist on
    if host['cloudinit']['userdata']:                                                                                                                   │ node 0cc47ae545dc
KeyError: 'cloudinit'                                                                                                                                   │[Wed23 16:16] - node.py           :32  :service-459a6e1f-8b1c-466f-9356-2c1d0ac4dc33 - INFO     - Monitoring node local
---------------------------------------------------------------------------                                                                             │[Wed23 16:16] - node.py           :78  :service-459a6e1f-8b1c-466f-9356-2c1d0ac4dc33 - INFO     - storage pool 0cc47ae545dc_fscache doesn't exist on
ErrorConditionObject                      Traceback (most recent call last)                                                                             │ node 0cc47ae545dc
/usr/local/bin/js9 in <module>()                                                                                                                        │[Wed23 16:16] - node.py           :32  :service-401db68f-189f-44a2-aabc-e16c97c4038a - INFO     - Monitoring node my_packet_node_service
----> 1 gw_service.schedule_action('install').wait(die=True)                                                                                            │[Wed23 16:16] - node.py           :78  :service-401db68f-189f-44a2-aabc-e16c97c4038a - INFO     - storage pool 0cc47ae545dc_fscache doesn't exist on
                                                                                                                                                        │ node 0cc47ae545dc
/opt/code/github/zero-os/0-robot/zerorobot/task/task.py in wait(self, timeout, die)                                                                     │[Wed23 16:17] - node.py           :32  :service-459a6e1f-8b1c-466f-9356-2c1d0ac4dc33 - INFO     - Monitoring node local
    156                 logger.critical('task is in error state, but no eco')                                                                           │[Wed23 16:17] - node.py           :78  :service-459a6e1f-8b1c-466f-9356-2c1d0ac4dc33 - INFO     - storage pool 0cc47ae545dc_fscache doesn't exist on
    157             else:                                                                                                                               │ node 0cc47ae545dc
--> 158                 raise self.eco                                                                                                                  │[Wed23 16:17] - node.py           :32  :service-401db68f-189f-44a2-aabc-e16c97c4038a - INFO     - Monitoring node my_packet_node_service
    159                                                                                                                                                 │[Wed23 16:17] - node.py           :78  :service-401db68f-189f-44a2-aabc-e16c97c4038a - INFO     - storage pool 0cc47ae545dc_fscache doesn't exist on
    160         return self                                                                                                                             │ node 0cc47ae545dc
                                                                                                                                                        │[Wed23 16:17] - node.py           :32  :service-459a6e1f-8b1c-466f-9356-2c1d0ac4dc33 - INFO     - Monitoring node local
ErrorConditionObject: 'cloudinit'
```

**Comment by grimpy** [comment]
This fixed on devleopment branch see https://github.com/Jumpscale/lib9/blob/development/JumpScale9Lib/clients/zero_os/sal/gateway/gateway.py#L226

**Comment by yveskerwyn** [comment]
But is this version of the SAL not included in the developement branch of ZOS?
