### ISSUE TITLE
disable vnc action doesn't work

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-templates#141]
try to disable vnc port on vm return the following error on the server : 
```
c-1e16cbd311a7 - ERROR    - error executing action disable_vnc:
Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-robot/zerorobot/template/state.py", line 78, in check
    state = self.get(category, tag)
  File "/opt/code/github/zero-os/0-robot/zerorobot/template/state.py", line 57, in get
    raise StateCategoryNotExistsError("category %s does not exist" % category)
zerorobot.template.state.StateCategoryNotExistsError: category vnc does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-robot/zerorobot/task/task.py", line 79, in execute
    self._result = self._func()
  File "/opt/code/github/zero-os/0-templates/templates/vm/vm.py", line 121, in disable_vnc
    self.state.check('vnc', self._vm_sal.info['vnc'], 'ok')
  File "/opt/code/github/zero-os/0-robot/zerorobot/template/state.py", line 85, in check
    raise StateCheckError(err_msg)
zerorobot.template.state.StateCheckError: check for state vnc:5902:ok failed

```
## Blueprint 
```
  - github.com/zero-os/0-templates/vm/0.0.1__904a4ded:
      memory: 2048
      nics:
        - type: default
          name: 07f9b8fc
      flist: https://hub.gig.tech/gig-bootable/ubuntu:16.04.flist

actions:
  - template: github.com/zero-os/0-templates/vm/0.0.1
    service: 904a4ded
    actions: ['disable_vnc']

```

**Comment by BolaNasr** [comment]
https://github.com/zero-os/0-templates/commit/10bc7d8509cc89dfed82255a38be40e9e0458df8

**Comment by islamTaha12** [comment]
it is working for me now

**Comment by Dinaamagdy** [comment]
worked on v1.4.1 version
