### ISSUE TITLE
minio : _backup_minio seems to work but print a lot of error messages

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-templates#92]
Related to story https://docs.greenitglobe.com/gig/org_development/issues/21

Just tested the templates.
Install, start, and stop are worked properly if i disable the `_backup_minio` feature.

the backup also seems to work, but it print a lot of error messages.
At `install`, looks like it won't work
```python
[Fri20 04:11] - minio.py          :62  :service-deb9af5d-a365-4530-9b90-51435282ef9b - INFO     - Installing minio backminio
[Fri20 04:11] - base.py           :201 :service-bcc570cd-4cf9-40ce-b649-72688d9dc2f0 - ERROR    - error executing action _backup_minio:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/template/state.py", line 78, in check
    state = self.get(category, tag)
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/template/state.py", line 64, in get
    raise StateCategoryNotExistsError("tag %s does not exist in category %s" % (tag, category))
zerorobot.template.state.StateCategoryNotExistsError: tag start does not exist in category actions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/task/task.py", line 78, in execute
    self._result = self.func()
  File "/opt/code/github/iwanbk/0-templates/templates/minio/minio.py", line 57, in _backup_minio
    self.state.check('actions', 'start', 'ok')
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/template/state.py", line 85, in check
    raise StateCheckError(err_msg)
zerorobot.template.state.StateCheckError: check for state actions:start:ok failed

ERROR:service-bcc570cd-4cf9-40ce-b649-72688d9dc2f0:error executing action _backup_minio:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/template/state.py", line 78, in check
    state = self.get(category, tag)
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/template/state.py", line 64, in get
    raise StateCategoryNotExistsError("tag %s does not exist in category %s" % (tag, category))
zerorobot.template.state.StateCategoryNotExistsError: tag start does not exist in category actions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/task/task.py", line 78, in execute
    self._result = self.func()
  File "/opt/code/github/iwanbk/0-templates/templates/minio/minio.py", line 57, in _backup_minio
    self.state.check('actions', 'start', 'ok')
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/template/state.py", line 85, in check
    raise StateCheckError(err_msg)
zerorobot.template.state.StateCheckError: check for state actions:start:ok failed

[Fri20 04:11] - Minio.py          :110 :ents.zero_os.sal.minio - INFO     - Creating minio config for backminio
[Fri20 04:11] - Restic.py         :27  :nts.zero_os.sal.restic - INFO     - Initializing repo s3:http://172.27.84.38:9000/deb9af5d-a365-4530-9b90-51435282ef9b
[Fri20 04:11] - base.py           :201 :service-deb9af5d-a365-4530-9b90-51435282ef9b - ERROR    - error executing action _backup_minio:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/template/state.py", line 78, in check
    state = self.get(category, tag)
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/template/state.py", line 64, in get
    raise StateCategoryNotExistsError("tag %s does not exist in category %s" % (tag, category))
zerorobot.template.state.StateCategoryNotExistsError: tag start does not exist in category actions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/task/task.py", line 78, in execute
    self._result = self.func()
  File "/opt/code/github/iwanbk/0-templates/templates/minio/minio.py", line 57, in _backup_minio
    self.state.check('actions', 'start', 'ok')
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/template/state.py", line 85, in check
    raise StateCheckError(err_msg)
zerorobot.template.state.StateCheckError: check for state actions:start:ok failed

ERROR:service-deb9af5d-a365-4530-9b90-51435282ef9b:error executing action _backup_minio:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/template/state.py", line 78, in check
    state = self.get(category, tag)
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/template/state.py", line 64, in get
    raise StateCategoryNotExistsError("tag %s does not exist in category %s" % (tag, category))
zerorobot.template.state.StateCategoryNotExistsError: tag start does not exist in category actions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/task/task.py", line 78, in execute
    self._result = self.func()
  File "/opt/code/github/iwanbk/0-templates/templates/minio/minio.py", line 57, in _backup_minio
    self.state.check('actions', 'start', 'ok')
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/template/state.py", line 85, in check
    raise StateCheckError(err_msg)
zerorobot.template.state.StateCheckError: check for state actions:start:ok failed

[Fri20 04:12] - base.py           :201 :service-deb9af5d-a365-4530-9b90-51435282ef9b - ERROR    - error executing action _backup_minio:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/template/state.py", line 78, in check
    state = self.get(category, tag)
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/template/state.py", line 64, in get
    raise StateCategoryNotExistsError("tag %s does not exist in category %s" % (tag, category))
zerorobot.template.state.StateCategoryNotExistsError: tag start does not exist in category actions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/task/task.py", line 78, in execute
    self._result = self.func()
  File "/opt/code/github/iwanbk/0-templates/templates/minio/minio.py", line 57, in _backup_minio
    self.state.check('actions', 'start', 'ok')
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/template/state.py", line 85, in check
    raise StateCheckError(err_msg)
zerorobot.template.state.StateCheckError: check for state actions:start:ok failed
```

After `start` it seems the backup is working, but still printing the error message.
```python
[Fri20 04:30] - base.py           :201 :service-bcc570cd-4cf9-40ce-b649-72688d9dc2f0 - ERROR    - error executing action _backup_minio:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/template/state.py", line 78, in check
    state = self.get(category, tag)
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/template/state.py", line 64, in get
    raise StateCategoryNotExistsError("tag %s does not exist in category %s" % (tag, category))
zerorobot.template.state.StateCategoryNotExistsError: tag start does not exist in category actions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/task/task.py", line 78, in execute
    self._result = self.func()
  File "/opt/code/github/iwanbk/0-templates/templates/minio/minio.py", line 57, in _backup_minio
    self.state.check('actions', 'start', 'ok')
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/template/state.py", line 85, in check
    raise StateCheckError(err_msg)
zerorobot.template.state.StateCheckError: check for state actions:start:ok failed

ERROR:service-bcc570cd-4cf9-40ce-b649-72688d9dc2f0:error executing action _backup_minio:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/template/state.py", line 78, in check
    state = self.get(category, tag)
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/template/state.py", line 64, in get
    raise StateCategoryNotExistsError("tag %s does not exist in category %s" % (tag, category))
zerorobot.template.state.StateCategoryNotExistsError: tag start does not exist in category actions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/task/task.py", line 78, in execute
    self._result = self.func()
  File "/opt/code/github/iwanbk/0-templates/templates/minio/minio.py", line 57, in _backup_minio
    self.state.check('actions', 'start', 'ok')
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/template/state.py", line 85, in check
    raise StateCheckError(err_msg)
zerorobot.template.state.StateCheckError: check for state actions:start:ok failed

[Fri20 04:30] - minio.py          :58  :service-deb9af5d-a365-4530-9b90-51435282ef9b - INFO     - Backing up minio backminio
INFO:service-deb9af5d-a365-4530-9b90-51435282ef9b:Backing up minio backminio
[Fri20 04:30] - Restic.py         :38  :nts.zero_os.sal.restic - INFO     - Backing up dir /bin/zerostor_meta to repo s3:http://172.27.84.38:9000/deb9af5d-a365-4530-9b90-51435282ef9b
STATE: 0 SUCCESS
STDOUT:
using parent snapshot 761a537f
scan [/bin/zerostor_meta]
[0:00] 3 directories, 0 files, 0B
scanned 3 directories, 0 files in 0:00
[0:00]   0B / 0B  3 / 3 items  0 errors  ETA 0:00 

duration: 0:00
snapshot 2d385094 saved

STDERR:

DATA:

```

**Comment by iwanbk** [comment]
Errored line is 

https://github.com/zero-os/0-templates/blob/abf41797f55c6b7dd9d9f74ae906d354e98203b4/templates/minio/minio.py#L57

wrap it inside `try-except` make the error messages disappear.
but don't think that it is the right way, it seems the best way is to fix the robot.

**Comment by serboctor** [comment]
We do checks like this everywhere and expect them to raise errors if the right state is not set yet. I dont really think it should be hidden. @zaibon what's your input regarding this?

**Comment by zaibon** [comment]
It is indeed normal, that is how the state.check work, it is expected to raise an exception that stop the flow.
